export const RULES_DEF = {
  "过滤": [
    { name: "AdBlock", defaultAction: "REJECT" },
    { name: "HTTPDNS", defaultAction: "REJECT" },
  ],
  "国际流媒体": [
    { name: "Netflix", defaultAction: "Proxy" },
    { name: "YouTube", defaultAction: "Proxy" },
    { name: "Spotify", defaultAction: "Proxy" },
    { name: "Disney Plus", defaultAction: "Proxy" },
    { name: "Max", defaultAction: "Proxy" },
    { name: "Amazon", defaultAction: "Proxy" },
    { name: "Apple TV", defaultAction: "Proxy" },
    { name: "Hulu", defaultAction: "Proxy" },
    { name: "BBC iPlayer", defaultAction: "Proxy" },
    { name: "Bahamut", defaultAction: "Proxy" },
  ],
  "国内流媒体": [
    { name: "Bilibili", defaultAction: "DIRECT" },
    { name: "IQIYI", defaultAction: "DIRECT" },
    { name: "Youku", defaultAction: "DIRECT" },
    { name: "Tencent Video", defaultAction: "DIRECT" },
    { name: "Netease Music", defaultAction: "DIRECT" },
  ],
  "社交通讯": [
    { name: "Telegram", defaultAction: "Proxy" },
    { name: "Discord", defaultAction: "Proxy" },
    { name: "TikTok", defaultAction: "Proxy" },
  ],
  "服务": [
    { name: "AI Suite", defaultAction: "Proxy" },
    { name: "Microsoft", defaultAction: "Proxy" },
    { name: "Apple", defaultAction: "Proxy" },
    { name: "Google FCM", defaultAction: "Proxy" },
    { name: "Steam", defaultAction: "DIRECT" },
    { name: "PayPal", defaultAction: "Proxy" },
    { name: "Scholar", defaultAction: "Proxy" },
    { name: "miHoYo", defaultAction: "DIRECT" },
  ],
  "通用": [
    { name: "Special", defaultAction: "DIRECT" },
    { name: "PROXY", defaultAction: "Proxy" },
    { name: "Domestic", defaultAction: "DIRECT" },
    { name: "Domestic IPs", defaultAction: "DIRECT" },
    { name: "LAN", defaultAction: "DIRECT" },
  ],
};

export const PROVIDER_URLS = {
  AdBlock: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/AdBlock.yaml",
  HTTPDNS: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/HTTPDNS.yaml",
  Special: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Special.yaml",
  PROXY: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Proxy.yaml",
  Domestic: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Domestic.yaml",
  "Domestic IPs": "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Domestic%20IPs.yaml",
  LAN: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/LAN.yaml",
  Netflix: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Media/Netflix.yaml",
  Spotify: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Media/Spotify.yaml",
  YouTube: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Media/YouTube.yaml",
  Max: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Media/Max.yaml",
  Bilibili: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Media/Bilibili.yaml",
  IQIYI: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Media/IQIYI.yaml",
  "Netease Music": "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Media/Netease%20Music.yaml",
  "Tencent Video": "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Media/Tencent%20Video.yaml",
  Youku: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Media/Youku.yaml",
  Amazon: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Media/Amazon.yaml",
  "Apple TV": "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Media/Apple%20TV.yaml",
  Bahamut: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Media/Bahamut.yaml",
  "BBC iPlayer": "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Media/BBC%20iPlayer.yaml",
  "Disney Plus": "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Media/Disney%20Plus.yaml",
  Hulu: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Media/Hulu.yaml",
  Telegram: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Telegram.yaml",
  Discord: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Discord.yaml",
  Steam: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Steam.yaml",
  TikTok: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/TikTok.yaml",
  PayPal: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/PayPal.yaml",
  Microsoft: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Microsoft.yaml",
  "AI Suite": "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/AI%20Suite.yaml",
  Apple: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Apple.yaml",
  "Google FCM": "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Google%20FCM.yaml",
  Scholar: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/Scholar.yaml",
  miHoYo: "https://raw.dler.io/dler-io/Rules/main/Clash/Provider/miHoYo.yaml",
};
